### ISSUE TITLE
TabularInline, StackedInline add and delete buttons don't work [Have solution]

### ISSUE THREAD

**Issue by vilkoz** [app-generator/django-admin-volt#17]
Example application `books`:
models.py:
```python
from django.db import models


# Create your models here.


class Book(models.Model):
    name = models.CharField(max_length=255, null=False)


class Author(models.Model):
    name = models.CharField(max_length=255, null=False)
    author = models.ForeignKey(Book, related_name="books", on_delete=models.CASCADE)
```
admin.py:
```python
from django.contrib import admin

from .models import Author, Book


# Register your models here.
@admin.register(Author)
class AuthorAdmin(admin.ModelAdmin):
    pass


class AuthorInline(admin.TabularInline):
    model = Author


@admin.register(Book)
class BookAdmin(admin.ModelAdmin):
    inlines = [AuthorInline]

```

When trying to create new book with multiple authors **there are no add-inline and delete-inline buttons**:

![screnshot](https://user-images.githubusercontent.com/16705559/222177405-43a1a29b-606f-4a48-bfa8-3fac8563fbb2.png)

prepopulate.js has the following problem
```js
'use strict';
{
    const $ = django.jQuery; //here
```

In django admin the `django.jQuery` or `window.django.jQuery` variable is declared inside `jquery.init.js` which is included in `admin/base.html` in block `{% block extrahead %}{% endblock %}`
But the `layouts/base.html` of this app doesn't have block `block extrahead`
![screen](https://user-images.githubusercontent.com/16705559/222179702-4d0d1311-b480-4055-bd9d-f71ce20b16be.png)

After adding `block extrahead` to `layouts/base.html` the above error is fixed, but new error appear:

![urls](https://user-images.githubusercontent.com/16705559/222180348-43241a5c-8235-4eae-b243-a39d0ed27b86.png)

It seems that background urls for `inline-detelink` and `...addlink` are wrong in `widgets.css` and `forms.css`:
```css
.inline-deletelink {
    float: right;
    text-indent: -9999px;
    background: url(../img/inline-delete.svg) 0 0 no-repeat;
    width: 16px;
    height: 16px;
    border: 0px none;
}
```

They lead to `/static/img/inline-delete.svg` but image is located in `/static/admin/img/inline-delete.svg`

When changed urls for `inline-delete.svg` and `icon-addlink.svg` from `../img` to `../admin/img` the problem is fixed:

![image](https://user-images.githubusercontent.com/16705559/222183660-913bbb49-69e7-4ea8-8472-631cace0c058.png)

### Conclusion

1. `block extrahead` should be in `layouts/base.html` 
2.  all background image urls in css files should be from `../admin/img/` instead of `../img/`

Will provide pull request soon

**Comment by app-generator** [comment]
Fix tagged and shipped in [v1.0.10](https://pypi.org/project/django-admin-volt/1.0.10/)

TY @vilkoz
