### ISSUE TITLE
collapse doesn't work

### ISSUE THREAD

**Issue by mohsensalare** [app-generator/django-admin-volt#21]
Hi
---

# Bug Report: collapse doesn't work in admin vote

<img width="1278" alt="Screenshot 1403-07-11 at 10 55 30 AM" src="https://github.com/user-attachments/assets/be7192a3-74fa-4078-89e1-f428ed0f2d6d">
<img width="1280" alt="Screenshot 1403-07-11 at 10 55 48 AM" src="https://github.com/user-attachments/assets/ec9fe4dd-84de-4e84-999b-b577d3c91c15">
<img width="1280" alt="Screenshot 1403-07-11 at 10 57 42 AM" src="https://github.com/user-attachments/assets/516db80f-d0ba-4e3a-b616-aabc222db462">

```
class Article(models.Model):
    title = models.CharField(max_length=200)
    content = FroalaField()
    tags = models.ManyToManyField(Tag, related_name="ArticleTags", verbose_name=_("tags"), blank=True)
    seo = models.JSONField()

    def __str__(self):
        return self.title
        
@admin.register(Article)
class ArticleAdmin(admin.ModelAdmin):
    fieldsets = (
        (_('Article Information'), {
            'fields': ('title', 'content', 'tags'),
            "classes": ["collapse"],
        }),
        (_('SEO Information'), {
            'fields': ('seo',),
            "classes": ["collapse"],
        }),
    )
```
 https://docs.djangoproject.com/en/5.1/ref/contrib/admin/

**Comment by mohsensalare** [comment]
@app-generator

**Comment by app-generator** [comment]
Hello! 

Sorry for the delay. The new AppSeed Service now manages the project and related issues:

https://app-generator.dev/ - Open-Source Platform.

Ty!
