### ISSUE TITLE
Error when trying to run: cannot import name 'smart_text' from 'django.utils.encoding'

### ISSUE THREAD

**Issue by dbartolomei** [app-generator/django-admin-volt#3]
I'm getting the following error after installing the admin template:

`Invalid template library specified. ImportError raised when trying to load 'admin_volt.templatetags.admin_volt': cannot import name 'smart_text' from 'django.utils.encoding'` 

I'm using Python 3.10.1 and Django 4.0

**Comment by dbartolomei** [comment]
Seems that `smart_text` was deprecated en Django 4.0

https://docs.djangoproject.com/en/4.0/internals/deprecation/

**Comment by app-generator** [comment]
Hello @dbartolomei 

The template is not tested with Django 4.0. 
We will get back soon as we can with a fix. 

BR

**Comment by app-generator** [comment]
@imankarimi in case you have the time, please make a test using Django 4.
Ty!

**Comment by imankarimi** [comment]
Hello @dbartolomei 
seems Django v4 removed smart_text, I changed the code to support this.
you can test it now

**Comment by app-generator** [comment]
Fixed - [v0.0.4](https://github.com/app-generator/django-admin-volt/releases)
PyPi - [django-admin-volt - v0.0.4](https://pypi.org/project/django-admin-volt/)

@dbartolomei - please update
@imankarimi - ty for your support 

Closing!
