### ISSUE TITLE
Django 4 Error: Cannot import name 'force_text' from 'django.utils.encoding' 

### ISSUE THREAD

**Issue by dbartolomei** [app-generator/django-admin-volt#4]
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'admin_volt.templatetags.admin_volt': cannot import name 'force_text' from 'django.utils.encoding' 

This is related to #3

**Comment by imankarimi** [comment]
Hello @dbartolomei
I solved the problem. you can reinstall it.

**Comment by app-generator** [comment]
Hello @imankarimi,

Ty for your fix. 
Let us know if the `patch` requires a new package release.

**Comment by imankarimi** [comment]
Hello @app-generator
Yes please

**Comment by app-generator** [comment]
Fix released in [v0.0.5](https://pypi.org/project/django-admin-volt/)

@dbartolomei please update. 
The fault is scheduled for closing soon.

**Comment by dbartolomei** [comment]
That did it! Thank you! @imankarimi
